export default {
  "3rd age kiteshield": {
    ac: 0,
    al: 0,
    am: -10,
    ar: -4,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 61,
    dl: 65,
    dm: -3,
    dr: 63,
    dt: 63,
    id: [10352],
    im: "3rd age kiteshield",
    pr: 0,
    vi: 1
  },
  "A chair": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [6122],
    im: "A chair",
    pr: 0,
    vi: 0
  },
  "Adamant defender": {
    ac: 11,
    al: 12,
    am: -3,
    ar: -2,
    at: 13,
    bm: 0,
    br: 0,
    bs: 4,
    dc: 11,
    dl: 12,
    dm: -3,
    dr: -2,
    dt: 13,
    id: [8849, 20459],
    im: "Adamant defender",
    pr: 0,
    vi: 1
  },
  "Adamant kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [1199],
    im: "Adamant kiteshield",
    pr: 0,
    vi: 1
  },
  "Adamant kiteshield (Arrav)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22127],
    im: "Adamant kiteshield (Arrav)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Asgarnia)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22129],
    im: "Adamant kiteshield (Asgarnia)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Dorgeshuun)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22131],
    im: "Adamant kiteshield (Dorgeshuun)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Dragon)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22133],
    im: "Adamant kiteshield (Dragon)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Fairy)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22135],
    im: "Adamant kiteshield (Fairy)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Guthix)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22137],
    im: "Adamant kiteshield (Guthix)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (HAM)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22139],
    im: "Adamant kiteshield (HAM)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Horse)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22141],
    im: "Adamant kiteshield (Horse)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Jogre)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22143],
    im: "Adamant kiteshield (Jogre)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Kandarin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22145],
    im: "Adamant kiteshield (Kandarin)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Misthalin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22147],
    im: "Adamant kiteshield (Misthalin)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Money)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22149],
    im: "Adamant kiteshield (Money)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Saradomin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22151],
    im: "Adamant kiteshield (Saradomin)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Skull)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22153],
    im: "Adamant kiteshield (Skull)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Varrock)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22155],
    im: "Adamant kiteshield (Varrock)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (Zamorak)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [22157],
    im: "Adamant kiteshield (Zamorak)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [2611],
    im: "Adamant kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Adamant kiteshield (t)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [2603],
    im: "Adamant kiteshield (t)",
    pr: 0,
    vi: 0
  },
  "Adamant shield (h1)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [7334],
    im: "Adamant shield (h1)",
    pr: 0,
    vi: 0
  },
  "Adamant shield (h2)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [7340],
    im: "Adamant shield (h2)",
    pr: 0,
    vi: 0
  },
  "Adamant shield (h3)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [7346],
    im: "Adamant shield (h3)",
    pr: 0,
    vi: 0
  },
  "Adamant shield (h4)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [7352],
    im: "Adamant shield (h4)",
    pr: 0,
    vi: 0
  },
  "Adamant shield (h5)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [7358],
    im: "Adamant shield (h5)",
    pr: 0,
    vi: 0
  },
  "Adamant sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 22,
    dl: 26,
    dm: 0,
    dr: 24,
    dt: 24,
    id: [1183],
    im: "Adamant sq shield",
    pr: 0,
    vi: 1
  },
  "Ancient d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 7,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 16,
    dl: 18,
    dm: 15,
    dr: 14,
    dt: 21,
    id: [23197],
    im: "Ancient d'hide shield",
    pr: 1,
    vi: 1
  },
  "Ancient kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [12468],
    im: "Ancient kiteshield",
    pr: 1,
    vi: 1
  },
  "Ancient wyvern shield": {
    ac: -10,
    al: -10,
    am: 15,
    ar: -10,
    at: -10,
    bm: 0,
    br: 0,
    bs: -2,
    dc: 75,
    dl: 80,
    dm: 15,
    dr: -5,
    dt: 72,
    id: [21633],
    im: "Ancient wyvern shield",
    pr: 0,
    vi: 1
  },
  "Ancient wyvern shield (uncharged)": {
    ac: -10,
    al: -10,
    am: 15,
    ar: -10,
    at: -10,
    bm: 0,
    br: 0,
    bs: -2,
    dc: 25,
    dl: 30,
    dm: 15,
    dr: -55,
    dt: 22,
    id: [21634],
    im: "Ancient wyvern shield (uncharged)",
    pr: 0,
    vi: 0
  },
  "Anti-dragon shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 8,
    dl: 9,
    dm: 2,
    dr: 8,
    dt: 7,
    id: [1540, 11710],
    im: "Anti-dragon shield",
    pr: 0,
    vi: 1
  },
  "Arcane spirit shield": {
    ac: 0,
    al: 0,
    am: 20,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 73,
    dl: 55,
    dm: 2,
    dr: 52,
    dt: 53,
    id: [12825],
    im: "Arcane spirit shield",
    pr: 3,
    vi: 1
  },
  "Armadyl d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 7,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 16,
    dl: 18,
    dm: 15,
    dr: 14,
    dt: 21,
    id: [23200],
    im: "Armadyl d'hide shield",
    pr: 1,
    vi: 1
  },
  "Armadyl kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [12478],
    im: "Armadyl kiteshield",
    pr: 1,
    vi: 1
  },
  "Avernic defender": {
    ac: 28,
    al: 29,
    am: -5,
    ar: -4,
    at: 30,
    bm: 0,
    br: 0,
    bs: 8,
    dc: 28,
    dl: 29,
    dm: -5,
    dr: -4,
    dt: 30,
    id: [22322, 22441],
    im: "Avernic defender",
    pr: 0,
    vi: 1
  },
  "Bandos d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 7,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 16,
    dl: 18,
    dm: 15,
    dr: 14,
    dt: 21,
    id: [23203],
    im: "Bandos d'hide shield",
    pr: 1,
    vi: 1
  },
  "Bandos kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [12488],
    im: "Bandos kiteshield",
    pr: 1,
    vi: 1
  },
  "Black d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 7,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 16,
    dl: 18,
    dm: 15,
    dr: 14,
    dt: 21,
    id: [22284],
    im: "Black d'hide shield",
    pr: 0,
    vi: 1
  },
  "Black defender": {
    ac: 7,
    al: 8,
    am: -3,
    ar: -2,
    at: 9,
    bm: 0,
    br: 0,
    bs: 2,
    dc: 7,
    dl: 8,
    dm: -3,
    dr: -2,
    dt: 9,
    id: [8847, 20455],
    im: "Black defender",
    pr: 0,
    vi: 1
  },
  "Black kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [1195],
    im: "Black kiteshield",
    pr: 0,
    vi: 1
  },
  "Black kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [2597],
    im: "Black kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Black kiteshield (t)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [2589],
    im: "Black kiteshield (t)",
    pr: 0,
    vi: 0
  },
  "Black satchel": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [10880],
    im: "Black satchel",
    pr: 0,
    vi: 0
  },
  "Black shield (h1)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [7332],
    im: "Black shield (h1)",
    pr: 0,
    vi: 0
  },
  "Black shield (h2)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [7338],
    im: "Black shield (h2)",
    pr: 0,
    vi: 0
  },
  "Black shield (h3)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [7344],
    im: "Black shield (h3)",
    pr: 0,
    vi: 0
  },
  "Black shield (h4)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [7350],
    im: "Black shield (h4)",
    pr: 0,
    vi: 0
  },
  "Black shield (h5)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [7356],
    im: "Black shield (h5)",
    pr: 0,
    vi: 0
  },
  "Black sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 16,
    dm: 0,
    dr: 15,
    dt: 15,
    id: [1179],
    im: "Black sq shield",
    pr: 0,
    vi: 1
  },
  "Blessed spirit shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 73,
    dl: 55,
    dm: 2,
    dr: 52,
    dt: 53,
    id: [12831],
    im: "Blessed spirit shield",
    pr: 3,
    vi: 1
  },
  "Blue d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 5,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 12,
    dl: 14,
    dm: 12,
    dr: 12,
    dt: 16,
    id: [22278],
    im: "Blue d'hide shield",
    pr: 0,
    vi: 1
  },
  "Blue gingerbread shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24431],
    im: "Blue gingerbread shield",
    pr: 0,
    vi: 0
  },
  "Book of balance": {
    ac: 4,
    al: 4,
    am: 4,
    ar: 4,
    at: 4,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 4,
    dl: 4,
    dm: 4,
    dr: 4,
    dt: 4,
    id: [3844],
    im: "Book of balance",
    pr: 5,
    vi: 1
  },
  "Book of darkness": {
    ac: 0,
    al: 0,
    am: 10,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [12612],
    im: "Book of darkness",
    pr: 5,
    vi: 1
  },
  "Book of law": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 10,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [12610],
    im: "Book of law",
    pr: 5,
    vi: 1
  },
  "Book of war": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 2,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [12608],
    im: "Book of war",
    pr: 5,
    vi: 1
  },
  Briefcase: {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [12335],
    im: "Briefcase",
    pr: 0,
    vi: 0
  },
  "Bronze defender": {
    ac: 1,
    al: 2,
    am: -3,
    ar: -2,
    at: 3,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 1,
    dl: 2,
    dm: -3,
    dr: -2,
    dt: 3,
    id: [8844, 20449],
    im: "Bronze defender",
    pr: 0,
    vi: 1
  },
  "Bronze kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 6,
    dl: 7,
    dm: -1,
    dr: 6,
    dt: 5,
    id: [1189],
    im: "Bronze kiteshield",
    pr: 0,
    vi: 1
  },
  "Bronze kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 6,
    dl: 7,
    dm: -1,
    dr: 6,
    dt: 5,
    id: [12213],
    im: "Bronze kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Bronze kiteshield (t)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 6,
    dl: 7,
    dm: -1,
    dr: 6,
    dt: 5,
    id: [12223],
    im: "Bronze kiteshield (t)",
    pr: 0,
    vi: 0
  },
  "Bronze sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 4,
    dl: 6,
    dm: 0,
    dr: 5,
    dt: 5,
    id: [1173],
    im: "Bronze sq shield",
    pr: 0,
    vi: 1
  },
  "Broodoo shield": {
    ac: 0,
    al: 0,
    am: 3,
    ar: -7,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 15,
    dl: 10,
    dm: 5,
    dr: 0,
    dt: 10,
    id: [6259, 6261, 6263, 6265, 6267, 6269, 6271, 6273, 6275, 6277, 6279],
    im: "Broodoo shield (blue)",
    pr: 5,
    vi: 1
  },
  "Broodoo shield (green)": {
    ac: 0,
    al: 0,
    am: 3,
    ar: -7,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 15,
    dl: 10,
    dm: 5,
    dr: 0,
    dt: 10,
    id: [6215, 6217, 6219, 6221, 6223, 6225, 6227, 6229, 6231, 6233, 6235],
    im: "Broodoo shield (green)",
    pr: 5,
    vi: 0
  },
  "Broodoo shield (orange)": {
    ac: 0,
    al: 0,
    am: 3,
    ar: -7,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 15,
    dl: 10,
    dm: 5,
    dr: 0,
    dt: 10,
    id: [6237, 6239, 6241, 6243, 6245, 6247, 6249, 6251, 6253, 6255, 6257],
    im: "Broodoo shield (orange)",
    pr: 5,
    vi: 0
  },
  "Cabbage round shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 22,
    dl: 26,
    dm: 0,
    dr: 24,
    dt: 24,
    id: [20272],
    im: "Cabbage round shield",
    pr: 0,
    vi: 0
  },
  "Chicken (Recruitment Drive)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [5609],
    im: "Chicken (Recruitment Drive)",
    pr: 0,
    vi: 0
  },
  Chronicle: {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [13660],
    im: "Chronicle",
    pr: 0,
    vi: 0
  },
  "Corrupted kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 9,
    dl: 10,
    dm: -1,
    dr: 9,
    dt: 8,
    id: [20846],
    im: "Corrupted kiteshield",
    pr: 0,
    vi: 0
  },
  "Cruciferous codex": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [13681],
    im: "Cruciferous codex",
    pr: 0,
    vi: 0
  },
  "Crystal shield": {
    ac: 0,
    al: 0,
    am: -10,
    ar: -10,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 53,
    dl: 54,
    dm: 0,
    dr: 80,
    dt: 51,
    id: [23991],
    im: "Crystal shield",
    pr: 0,
    vi: 1
  },
  "Crystal shield (i)": {
    ac: 0,
    al: 0,
    am: -10,
    ar: -10,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 53,
    dl: 54,
    dm: 0,
    dr: 80,
    dt: 51,
    id: [
      11759,
      11760,
      11761,
      11762,
      11763,
      11764,
      11765,
      11766,
      11767,
      11768,
      11769
    ],
    im: "Crystal shield",
    pr: 0,
    vi: 0
  },
  "Damaged book (Ancient)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [12611],
    im: "Damaged book (Ancient)",
    pr: 5,
    vi: 0
  },
  "Damaged book (Armadyl)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [12609],
    im: "Damaged book (Armadyl)",
    pr: 5,
    vi: 0
  },
  "Damaged book (Bandos)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [12607],
    im: "Damaged book (Bandos)",
    pr: 5,
    vi: 0
  },
  "Damaged book (Guthix)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [3843],
    im: "Damaged book (Guthix)",
    pr: 5,
    vi: 0
  },
  "Damaged book (Saradomin)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [3839],
    im: "Damaged book (Saradomin)",
    pr: 5,
    vi: 0
  },
  "Damaged book (Zamorak)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [3841],
    im: "Damaged book (Zamorak)",
    pr: 5,
    vi: 0
  },
  "Decorative shield (gold)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [4512, 20491],
    im: "Decorative shield (gold)",
    pr: 0,
    vi: 1
  },
  "Decorative shield (red)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [4072],
    im: "Decorative shield (red)",
    pr: 0,
    vi: 1
  },
  "Decorative shield (white)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 20,
    dl: 22,
    dm: -1,
    dr: 20,
    dt: 18,
    id: [4507],
    im: "Decorative shield (white)",
    pr: 0,
    vi: 1
  },
  "Defensive shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 7,
    dl: 9,
    dm: 0,
    dr: 7,
    dt: 8,
    id: [8856],
    im: "Defensive shield",
    pr: 0,
    vi: 0
  },
  "Dragon defender": {
    ac: 23,
    al: 24,
    am: -3,
    ar: -2,
    at: 25,
    bm: 0,
    br: 0,
    bs: 6,
    dc: 23,
    dl: 24,
    dm: -3,
    dr: -2,
    dt: 25,
    id: [12954, 20463],
    im: "Dragon defender",
    pr: 0,
    vi: 1
  },
  "Dragon defender (t)": {
    ac: 23,
    al: 24,
    am: -3,
    ar: -2,
    at: 25,
    bm: 0,
    br: 0,
    bs: 6,
    dc: 23,
    dl: 24,
    dm: -3,
    dr: -2,
    dt: 25,
    id: [19722],
    im: "Dragon defender (t)",
    pr: 0,
    vi: 0
  },
  "Dragon kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 58,
    dl: 60,
    dm: -1,
    dr: 58,
    dt: 56,
    id: [21895],
    im: "Dragon kiteshield",
    pr: 0,
    vi: 1
  },
  "Dragon kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 58,
    dl: 60,
    dm: -1,
    dr: 58,
    dt: 56,
    id: [22244],
    im: "Dragon kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Dragon sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 48,
    dl: 52,
    dm: 0,
    dr: 50,
    dt: 50,
    id: [1187],
    im: "Dragon sq shield",
    pr: 0,
    vi: 1
  },
  "Dragon sq shield (g)": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 48,
    dl: 52,
    dm: 0,
    dr: 50,
    dt: 50,
    id: [12418],
    im: "Dragon sq shield (g)",
    pr: 0,
    vi: 0
  },
  "Dragonfire shield": {
    ac: 0,
    al: 0,
    am: -10,
    ar: -5,
    at: 0,
    bm: 0,
    br: 0,
    bs: 7,
    dc: 72,
    dl: 75,
    dm: 10,
    dr: 72,
    dt: 70,
    id: [11283],
    im: "Dragonfire shield",
    pr: 0,
    vi: 1
  },
  "Dragonfire shield (uncharged)": {
    ac: 0,
    al: 0,
    am: -10,
    ar: -5,
    at: 0,
    bm: 0,
    br: 0,
    bs: 7,
    dc: 22,
    dl: 25,
    dm: 10,
    dr: 22,
    dt: 20,
    id: [11284],
    im: "Dragonfire shield (uncharged)",
    pr: 0,
    vi: 0
  },
  "Dragonfire ward": {
    ac: -10,
    al: -10,
    am: -10,
    ar: 15,
    at: -10,
    bm: 0,
    br: 0,
    bs: -2,
    dc: 28,
    dl: 30,
    dm: 28,
    dr: 68,
    dt: 25,
    id: [22002],
    im: "Dragonfire ward",
    pr: 0,
    vi: 1
  },
  "Dragonfire ward (uncharged)": {
    ac: -10,
    al: -10,
    am: -10,
    ar: 15,
    at: -10,
    bm: 0,
    br: 0,
    bs: -2,
    dc: -22,
    dl: -20,
    dm: 28,
    dr: 18,
    dt: -25,
    id: [22003],
    im: "Dragonfire ward (uncharged)",
    pr: 0,
    vi: 0
  },
  "Elemental shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 6,
    dr: 0,
    dt: 0,
    id: [2890],
    im: "Elemental shield",
    pr: 0,
    vi: 1
  },
  "Elysian spirit shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 75,
    dl: 65,
    dm: 2,
    dr: 57,
    dt: 63,
    id: [12817],
    im: "Elysian spirit shield",
    pr: 3,
    vi: 1
  },
  "Falador shield 1": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 9,
    dl: 10,
    dm: -1,
    dr: 9,
    dt: 8,
    id: [13117],
    im: "Falador shield 1",
    pr: 1,
    vi: 1
  },
  "Falador shield 2": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [13118],
    im: "Falador shield 2",
    pr: 3,
    vi: 1
  },
  "Falador shield 3": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 20,
    dl: 22,
    dm: -1,
    dr: 20,
    dt: 18,
    id: [13119],
    im: "Falador shield 3",
    pr: 4,
    vi: 1
  },
  "Falador shield 4": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [13120],
    im: "Falador shield 4",
    pr: 5,
    vi: 1
  },
  "Fremennik shield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [3758],
    im: "Fremennik shield",
    pr: 0,
    vi: 0
  },
  "Gilded kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [3488],
    im: "Gilded kiteshield",
    pr: 0,
    vi: 0
  },
  "Gilded sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 36,
    dl: 40,
    dm: 0,
    dr: 38,
    dt: 38,
    id: [20152],
    im: "Gilded sq shield",
    pr: 0,
    vi: 0
  },
  "Gingerbread shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24437],
    im: "Gingerbread shield",
    pr: 0,
    vi: 0
  },
  "Gold satchel": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [10881],
    im: "Gold satchel",
    pr: 0,
    vi: 0
  },
  "Granite shield": {
    ac: 0,
    al: 0,
    am: -12,
    ar: -8,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 38,
    dl: 42,
    dm: 0,
    dr: 65,
    dt: 40,
    id: [3122],
    im: "Granite shield",
    pr: 0,
    vi: 1
  },
  "Green d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 4,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 11,
    dl: 12,
    dm: 9,
    dr: 11,
    dt: 14,
    id: [22275],
    im: "Green d'hide shield",
    pr: 0,
    vi: 1
  },
  "Green gingerbread shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24428],
    im: "Green gingerbread shield",
    pr: 0,
    vi: 0
  },
  "Green satchel": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [10878],
    im: "Green satchel",
    pr: 0,
    vi: 0
  },
  "Guthix d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 7,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 16,
    dl: 18,
    dm: 15,
    dr: 14,
    dt: 21,
    id: [23188],
    im: "Guthix d'hide shield",
    pr: 1,
    vi: 1
  },
  "Guthix kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [2675],
    im: "Guthix kiteshield",
    pr: 1,
    vi: 1
  },
  "Hard leather shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 2,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 7,
    dl: 7,
    dm: 5,
    dr: 9,
    dt: 8,
    id: [22269],
    im: "Hard leather shield",
    pr: 0,
    vi: 1
  },
  "Holy book": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 8,
    dl: 8,
    dm: 8,
    dr: 8,
    dt: 8,
    id: [3840],
    im: "Holy book",
    pr: 5,
    vi: 1
  },
  "Iced gingerbread shield (blue)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24440],
    im: "Blue gingerbread shield",
    pr: 0,
    vi: 0
  },
  "Iced gingerbread shield (green)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24438],
    im: "Green gingerbread shield",
    pr: 0,
    vi: 0
  },
  "Iced gingerbread shield (red)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24439],
    im: "Red gingerbread shield",
    pr: 0,
    vi: 0
  },
  "Iron defender": {
    ac: 3,
    al: 4,
    am: -3,
    ar: -2,
    at: 5,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 3,
    dl: 4,
    dm: -3,
    dr: -2,
    dt: 5,
    id: [8845, 20451],
    im: "Iron defender",
    pr: 0,
    vi: 1
  },
  "Iron kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 9,
    dl: 10,
    dm: -1,
    dr: 9,
    dt: 8,
    id: [1191],
    im: "Iron kiteshield",
    pr: 0,
    vi: 1
  },
  "Iron kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 9,
    dl: 10,
    dm: -1,
    dr: 9,
    dt: 8,
    id: [12243],
    im: "Iron kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Iron kiteshield (t)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 9,
    dl: 10,
    dm: -1,
    dr: 9,
    dt: 8,
    id: [12233],
    im: "Iron kiteshield (t)",
    pr: 0,
    vi: 0
  },
  "Iron sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 7,
    dl: 9,
    dm: 0,
    dr: 8,
    dt: 8,
    id: [1175],
    im: "Iron sq shield",
    pr: 0,
    vi: 1
  },
  "Kharedst's memoirs": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [21760],
    im: "Kharedst's memoirs",
    pr: 1,
    vi: 0
  },
  "Lit bug lantern": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [7053],
    im: "Lit bug lantern",
    pr: 0,
    vi: 1
  },
  "Mage's book": {
    ac: 0,
    al: 0,
    am: 15,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 15,
    dr: 0,
    dt: 0,
    id: [6889],
    im: "Mage's book",
    pr: 0,
    vi: 1
  },
  "Magic shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 9,
    dl: 13,
    dm: 3,
    dr: 9,
    dt: 10,
    id: [22263],
    im: "Magic shield",
    pr: 0,
    vi: 1
  },
  "Malediction ward": {
    ac: -8,
    al: -8,
    am: 12,
    ar: -12,
    at: -8,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 48,
    dl: 52,
    dm: 15,
    dr: 0,
    dt: 50,
    id: [11924],
    im: "Malediction ward",
    pr: 0,
    vi: 1
  },
  "Malediction ward (or)": {
    ac: -8,
    al: -8,
    am: 12,
    ar: -12,
    at: -8,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 48,
    dl: 52,
    dm: 15,
    dr: 0,
    dt: 50,
    id: [12806],
    im: "Malediction ward (or)",
    pr: 0,
    vi: 0
  },
  "Maple shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 6,
    dl: 8,
    dm: 2,
    dr: 7,
    dt: 7,
    id: [22257],
    im: "Maple shield",
    pr: 0,
    vi: 1
  },
  "Mind shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 9,
    dr: 0,
    dt: 0,
    id: [9731],
    im: "Mind shield",
    pr: 0,
    vi: 1
  },
  "Mirror shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 5,
    dl: 15,
    dm: 5,
    dr: 10,
    dt: 10,
    id: [4156],
    im: "Mirror shield",
    pr: 0,
    vi: 1
  },
  "Mithril defender": {
    ac: 8,
    al: 9,
    am: -3,
    ar: -2,
    at: 10,
    bm: 0,
    br: 0,
    bs: 3,
    dc: 8,
    dl: 9,
    dm: -3,
    dr: -2,
    dt: 10,
    id: [8848, 20457],
    im: "Mithril defender",
    pr: 0,
    vi: 1
  },
  "Mithril kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 20,
    dl: 22,
    dm: -1,
    dr: 20,
    dt: 18,
    id: [1197],
    im: "Mithril kiteshield",
    pr: 0,
    vi: 1
  },
  "Mithril kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 20,
    dl: 22,
    dm: -1,
    dr: 20,
    dt: 18,
    id: [12281],
    im: "Mithril kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Mithril kiteshield (t)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 20,
    dl: 22,
    dm: -1,
    dr: 20,
    dt: 18,
    id: [12291],
    im: "Mithril kiteshield (t)",
    pr: 0,
    vi: 0
  },
  "Mithril sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 15,
    dl: 19,
    dm: 0,
    dr: 17,
    dt: 17,
    id: [1181],
    im: "Mithril sq shield",
    pr: 0,
    vi: 1
  },
  "Neitiznot shield": {
    ac: 0,
    al: 0,
    am: -10,
    ar: -10,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 31,
    dl: 17,
    dm: -4,
    dr: 33,
    dt: 17,
    id: [10826],
    im: "Neitiznot shield",
    pr: 0,
    vi: 1
  },
  None: {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [-1],
    im: "Shield_slot",
    pr: 0,
    vi: 0
  },
  "Oak shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 4,
    dl: 6,
    dm: 1,
    dr: 5,
    dt: 5,
    id: [22251],
    im: "Oak shield",
    pr: 0,
    vi: 1
  },
  "Odium ward": {
    ac: -12,
    al: -12,
    am: -8,
    ar: 12,
    at: -12,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 24,
    dr: 52,
    dt: 0,
    id: [11926],
    im: "Odium ward",
    pr: 0,
    vi: 1
  },
  "Odium ward (or)": {
    ac: -12,
    al: -12,
    am: -8,
    ar: 12,
    at: -12,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 24,
    dr: 52,
    dt: 0,
    id: [12807],
    im: "Odium ward (or)",
    pr: 0,
    vi: 0
  },
  "Plain satchel": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [10877],
    im: "Plain satchel",
    pr: 0,
    vi: 0
  },
  "Pumpkin lantern": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24326],
    im: "Pumpkin lantern",
    pr: 0,
    vi: 0
  },
  "Red d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 6,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 16,
    dm: 13,
    dr: 13,
    dt: 18,
    id: [22281],
    im: "Red d'hide shield",
    pr: 0,
    vi: 1
  },
  "Red gingerbread shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24430],
    im: "Red gingerbread shield",
    pr: 0,
    vi: 0
  },
  "Red satchel": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [10879],
    im: "Red satchel",
    pr: 0,
    vi: 0
  },
  "Redwood shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 11,
    dl: 15,
    dm: 4,
    dr: 10,
    dt: 12,
    id: [22266],
    im: "Redwood shield",
    pr: 0,
    vi: 1
  },
  "Rune defender": {
    ac: 18,
    al: 19,
    am: -3,
    ar: -2,
    at: 20,
    bm: 0,
    br: 0,
    bs: 5,
    dc: 18,
    dl: 19,
    dm: -3,
    dr: -2,
    dt: 20,
    id: [8850, 20461],
    im: "Rune defender",
    pr: 0,
    vi: 1
  },
  "Rune defender (t)": {
    ac: 18,
    al: 19,
    am: -3,
    ar: -2,
    at: 20,
    bm: 0,
    br: 0,
    bs: 5,
    dc: 18,
    dl: 19,
    dm: -3,
    dr: -2,
    dt: 20,
    id: [23230],
    im: "Rune defender (t)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [1201],
    im: "Rune kiteshield",
    pr: 0,
    vi: 1
  },
  "Rune kiteshield (Arrav)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8714],
    im: "Rune kiteshield (Arrav)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Asgarnia)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8716],
    im: "Rune kiteshield (Asgarnia)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Dorgeshuun)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8718],
    im: "Rune kiteshield (Dorgeshuun)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Dragon)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8720],
    im: "Rune kiteshield (Dragon)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Fairy)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8722],
    im: "Rune kiteshield (Fairy)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Guthix)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8724],
    im: "Rune kiteshield (Guthix)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (HAM)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8726],
    im: "Rune kiteshield (HAM)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Horse)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8728],
    im: "Rune kiteshield (Horse)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Jogre)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8730],
    im: "Rune kiteshield (Jogre)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Kandarin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8732],
    im: "Rune kiteshield (Kandarin)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Misthalin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8734],
    im: "Rune kiteshield (Misthalin)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Money)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8736],
    im: "Rune kiteshield (Money)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Saradomin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8738],
    im: "Rune kiteshield (Saradomin)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Skull)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8740],
    im: "Rune kiteshield (Skull)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Varrock)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8742],
    im: "Rune kiteshield (Varrock)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (Zamorak)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [8744],
    im: "Rune kiteshield (Zamorak)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [2621],
    im: "Rune kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Rune kiteshield (t)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [2629],
    im: "Rune kiteshield (t)",
    pr: 0,
    vi: 0
  },
  "Rune satchel": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [10882],
    im: "Rune satchel",
    pr: 0,
    vi: 0
  },
  "Rune shield (h1)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [7336],
    im: "Rune shield (h1)",
    pr: 0,
    vi: 0
  },
  "Rune shield (h2)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [7342],
    im: "Rune shield (h2)",
    pr: 0,
    vi: 0
  },
  "Rune shield (h3)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [7348],
    im: "Rune shield (h3)",
    pr: 0,
    vi: 0
  },
  "Rune shield (h4)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [7354],
    im: "Rune shield (h4)",
    pr: 0,
    vi: 0
  },
  "Rune shield (h5)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [7360],
    im: "Rune shield (h5)",
    pr: 0,
    vi: 0
  },
  "Rune sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 36,
    dl: 40,
    dm: 0,
    dr: 38,
    dt: 38,
    id: [1185],
    im: "Rune sq shield",
    pr: 0,
    vi: 1
  },
  "Runefest shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [21695],
    im: "Runefest shield",
    pr: 0,
    vi: 0
  },
  "Saradomin d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 7,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 16,
    dl: 18,
    dm: 15,
    dr: 14,
    dt: 21,
    id: [23191],
    im: "Saradomin d'hide shield",
    pr: 1,
    vi: 1
  },
  "Saradomin kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [2667],
    im: "Saradomin kiteshield",
    pr: 1,
    vi: 1
  },
  "Siren's tome": {
    ac: 0,
    al: 0,
    am: 15,
    ar: 0,
    at: 0,
    bm: 4,
    br: 0,
    bs: 0,
    dc: -10,
    dl: -10,
    dm: 15,
    dr: -10,
    dt: -10,
    id: [24418],
    im: "Siren's tome",
    pr: -5,
    vi: 1
  },
  "Snakeskin shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 3,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 8,
    dl: 9,
    dm: 7,
    dr: 10,
    dt: 10,
    id: [22272],
    im: "Snakeskin shield",
    pr: 0,
    vi: 1
  },
  "Spectral spirit shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 73,
    dl: 55,
    dm: 30,
    dr: 52,
    dt: 53,
    id: [12821],
    im: "Spectral spirit shield",
    pr: 3,
    vi: 1
  },
  "Spirit shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 50,
    dl: 41,
    dm: 1,
    dr: 45,
    dt: 39,
    id: [12829],
    im: "Spirit shield",
    pr: 1,
    vi: 1
  },
  "Steel defender": {
    ac: 5,
    al: 6,
    am: -3,
    ar: -2,
    at: 7,
    bm: 0,
    br: 0,
    bs: 1,
    dc: 5,
    dl: 6,
    dm: -3,
    dr: -2,
    dt: 7,
    id: [8846, 20453],
    im: "Steel defender",
    pr: 0,
    vi: 1
  },
  "Steel kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [1193],
    im: "Steel kiteshield",
    pr: 0,
    vi: 1
  },
  "Steel kiteshield (Arrav)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8746],
    im: "Steel kiteshield (Arrav)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Asgarnia)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8748],
    im: "Steel kiteshield (Asgarnia)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Dorgeshuun)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8750],
    im: "Steel kiteshield (Dorgeshuun)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Dragon)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8752],
    im: "Steel kiteshield (Dragon)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Fairy)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8754],
    im: "Steel kiteshield (Fairy)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Guthix)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8756],
    im: "Steel kiteshield (Guthix)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (HAM)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8758],
    im: "Steel kiteshield (HAM)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Horse)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8760],
    im: "Steel kiteshield (Horse)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Jogre)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8762],
    im: "Steel kiteshield (Jogre)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Kandarin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8764],
    im: "Steel kiteshield (Kandarin)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Misthalin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8766],
    im: "Steel kiteshield (Misthalin)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Money)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8768],
    im: "Steel kiteshield (Money)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Saradomin)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8770],
    im: "Steel kiteshield (Saradomin)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Skull)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8772],
    im: "Steel kiteshield (Skull)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Varrock)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8774],
    im: "Steel kiteshield (Varrock)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (Zamorak)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [8776],
    im: "Steel kiteshield (Zamorak)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (g)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [20181],
    im: "Steel kiteshield (g)",
    pr: 0,
    vi: 0
  },
  "Steel kiteshield (t)": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 15,
    dm: -1,
    dr: 14,
    dt: 13,
    id: [20196],
    im: "Steel kiteshield (t)",
    pr: 0,
    vi: 0
  },
  "Steel sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 11,
    dl: 13,
    dm: 0,
    dr: 12,
    dt: 12,
    id: [1177],
    im: "Steel sq shield",
    pr: 0,
    vi: 1
  },
  "Toktz-ket-xil": {
    ac: 0,
    al: 0,
    am: -12,
    ar: -8,
    at: 0,
    bm: 0,
    br: 0,
    bs: 5,
    dc: 38,
    dl: 42,
    dm: 0,
    dr: 65,
    dt: 40,
    id: [6524],
    im: "Toktz-ket-xil",
    pr: 0,
    vi: 0
  },
  "Tome of fire": {
    ac: 0,
    al: 0,
    am: 8,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 8,
    dr: 0,
    dt: 0,
    id: [20714],
    im: "Tome of fire",
    pr: 0,
    vi: 1
  },
  "Tome of fire (empty)": {
    ac: 0,
    al: 0,
    am: 8,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 8,
    dr: 0,
    dt: 0,
    id: [20716],
    im: "Tome of fire (empty)",
    pr: 0,
    vi: 0
  },
  "Training shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 3,
    dl: 5,
    dm: 1,
    dr: 4,
    dt: 4,
    id: [9704],
    im: "Training shield",
    pr: 0,
    vi: 1
  },
  "Twisted buckler": {
    ac: -7,
    al: -8,
    am: -10,
    ar: 18,
    at: -7,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 22,
    dl: 24,
    dm: 26,
    dr: 58,
    dt: 22,
    id: [21000],
    im: "Twisted buckler",
    pr: 0,
    vi: 1
  },
  "Twisted league bronze trophy": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24384],
    im: "Twisted league bronze trophy",
    pr: 0,
    vi: 0
  },
  "Twisted league iron trophy": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24382],
    im: "Twisted league iron trophy",
    pr: 0,
    vi: 0
  },
  "Twisted league mithril trophy": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24378],
    im: "Twisted league mithril trophy",
    pr: 0,
    vi: 0
  },
  "Twisted league steel trophy": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [24380],
    im: "Twisted league steel trophy",
    pr: 0,
    vi: 0
  },
  "Unholy book": {
    ac: 8,
    al: 8,
    am: 8,
    ar: 8,
    at: 8,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [3842],
    im: "Unholy book",
    pr: 5,
    vi: 1
  },
  "Unlit bug lantern": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [7051],
    im: "Unlit bug lantern",
    pr: 0,
    vi: 0
  },
  "V's shield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 29,
    dl: 31,
    dm: -1,
    dr: 29,
    dt: 27,
    id: [24265, 24266],
    im: "V's shield",
    pr: 0,
    vi: 1
  },
  "White kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 18,
    dl: 19,
    dm: -1,
    dr: 18,
    dt: 17,
    id: [6633],
    im: "White kiteshield",
    pr: 1,
    vi: 1
  },
  "White sq shield": {
    ac: 0,
    al: 0,
    am: -6,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 14,
    dl: 16,
    dm: 0,
    dr: 15,
    dt: 15,
    id: [6631],
    im: "White sq shield",
    pr: 1,
    vi: 1
  },
  "Willow shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 5,
    dl: 7,
    dm: 2,
    dr: 6,
    dt: 6,
    id: [22254],
    im: "Willow shield",
    pr: 0,
    vi: 1
  },
  "Wooden shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 3,
    dl: 5,
    dm: 1,
    dr: 4,
    dt: 4,
    id: [1171],
    im: "Wooden shield",
    pr: 0,
    vi: 1
  },
  "Wooden shield (Weapons rack)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 0,
    dl: 0,
    dm: 0,
    dr: 0,
    dt: 0,
    id: [7676],
    im: "Wooden shield (Weapons rack)",
    pr: 0,
    vi: 0
  },
  "Wooden shield (g)": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 3,
    dl: 5,
    dm: 1,
    dr: 4,
    dt: 4,
    id: [20166],
    im: "Wooden shield (g)",
    pr: 0,
    vi: 0
  },
  "Yew shield": {
    ac: 0,
    al: 0,
    am: 0,
    ar: 0,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 7,
    dl: 9,
    dm: 3,
    dr: 8,
    dt: 8,
    id: [22260],
    im: "Yew shield",
    pr: 0,
    vi: 1
  },
  "Zamorak d'hide shield": {
    ac: -11,
    al: -15,
    am: -10,
    ar: 7,
    at: -15,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 16,
    dl: 18,
    dm: 15,
    dr: 14,
    dt: 21,
    id: [23194],
    im: "Zamorak d'hide shield",
    pr: 1,
    vi: 1
  },
  "Zamorak kiteshield": {
    ac: 0,
    al: 0,
    am: -8,
    ar: -2,
    at: 0,
    bm: 0,
    br: 0,
    bs: 0,
    dc: 46,
    dl: 48,
    dm: -1,
    dr: 46,
    dt: 44,
    id: [2659],
    im: "Zamorak kiteshield",
    pr: 1,
    vi: 1
  }
};
